### ISSUE TITLE
Add Config Option for Tag Service Name

### ISSUE THREAD

**Issue by HunHage** [GoAwayNow/HydrausNao#7]
I ran into an issue on [Line #97](https://github.com/GoAwayNow/HydrausNao/blob/63ddc269e07d9f288e157cd5011fe9049bc102c5/hydrus_saucenao_search.py#L97) where the script tries to fetch the `my tags` service. I don't know why but my tag service is named `local tags` instead, this leads to the script crashing since the tags service can't be found. Simply changing the name to match my tag service name resolved this issue.

I'm no real python developer, but I do think I could make a PR to add this option myself if you would accept the merge.

**Comment by HunHage** [comment]
I went ahead and created a pull request since I needed to process some more files and thus had a set to test with.

As a side note I noticed there are a lot of unused dependencies, notably:
- os
- io
- unicodedata
- requests
- hydrus
- OrderedDict

However I don't know that much about python either, so I'm not sure if these are needed for versions other than 3.8.

**Comment by GoAwayNow** [comment]
Hey, I didn't know anyone else was actually using this script! Sweet!

I thought something like this might happen, so the option actually already exists in the script. I left it undocumented because I didn't want people dumping tons of stuff onto the PTR. It functions exactly the same as with your changes, it just has its default set in the script instead of config_default.ini.

Line 97 looks for a key called service under the Hydrus_Meta_Tags section, and uses "my tags" if it fails. I must admit, I've never tested it before, but I just checked by changing the default to something else and setting the service in config.ini and it seems to work just fine.

As for the dependencies, with os, io and unicodedata, I'm unsure if they're needed, but they're as used as they were in the example I used as a base for this, so I've left them alone for now. Requests was left on purpose, because I'm using it in the update I just pushed. OrderedDict was left as a mistake, however.

All that said, the script crashing isn't something I had anticipated, and it does need to be handled. Thanks for letting me know.

**Comment by HunHage** [comment]
That's all fine, thanks for the response. I did notice that the functionality was already there after opening the issue but decided to make the change anyway so it's easier to see within the config file. The people on the Discord server are aware of your script and do reference it when people ask about IQDB/SauceNao tagging, yours is the only one that does SauceNAO it seems!

People dumping to the PTR is in fact an issue, I don't use the PTR myself. So that may be why my tags service is named differently. A 25GB download is a steep investment for debugging as well. If you don't want to merge my changes that is ok since they don't account for the PTR issues this might create. Bad PTR additions are a frequent gripe on the discord and I wouldn't want to contribute to that.

**Comment by GoAwayNow** [comment]
> The people on the Discord server are aware of your script and do reference it when people ask about IQDB/SauceNao tagging, yours is the only one that does SauceNAO it seems!
Neat!

Lol, anyway, I looked into why your service might be tagged differently because I seemed to remember a mention of the tag service default name being changed a while back, and I found it in the [v368 changelog.](https://hydrus.tumblr.com/post/187808432724/version-368) 

I'm not really sure whether I want to make this change or just add information about it to the except expression I'm going to add. On one hand, the chances of people willfully making the config change to add these tags to the PTR is pretty low. On the other hand, this issue should also be really rare, only realistically being an issue for users on very old clients, or those who have manually renamed their tag service.

**Comment by HunHage** [comment]
> I found it in the [v368 changelog.](https://hydrus.tumblr.com/post/187808432724/version-368)

With that context it leads me to believe the reason my service is named differently is due to some sort of bug on the Hydrus side, I did test by installing a clean (portable) instance of 367 and updated to 368  (and again from 367 to 380) to verify that it does rename the tag service, so I'm not sure what happened!

I can't provide a source because I don't know how to since this is on the Discord, but HyDev did hold a vote on what features people wanted. The number one vote was to allow for multiple local *file* services. I'm not sure how that will affect the tag services but it wouldn't be a truly separate file service if it shared tags across them.

I think the best option with this knowledge is as you said, to add the except with a message about setting the tag service name in the config. As even if the tags services change to have different default names that message would still point people in the right direction.

**Comment by GoAwayNow** [comment]
>The number one vote was to allow for multiple local file services.
Oh my. Well, that's gonna mean major changes to just about every system, so I don't expect we'll see that for a while at least.

Anyway, with the tagging refactored into a single function, I can add the except. It should only take a few minutes. With that, I guess I'll close this issue, even if it's a somewhat different outcome than intended.
